version: '3.9'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:${VERSION}"
    container_name: singleElasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      node.name: elasticsearch
      cluster.name: elasticsearch-cluster
      network.host: "0.0.0.0"
      network.bind_host: "0.0.0.0"
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      xpack.security.enabled: false
      xpack.monitoring.enabled: false
      xpack.monitoring.collection.enabled: false
      script.painless.regex.enabled: true
    ports:
      - 9200:9200
    privileged: true
  kibana:
    image: "docker.elastic.co/kibana/kibana:${VERSION}"
    container_name: singleKibana
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: 5601
      ELASTICSEARCH_HOSTS: http://singleElasticsearch:9200
    ports:
      - 5601:5601

